/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_data_scan_ImageProcess */

#ifndef _Included_com_jch_test_Logger
#define _Included_com_jch_test_Logger
#define FALSE JNI_FALSE
#define TRUE JNI_TRUE
#define ARR_LEN(x) ((int) (sizeof(x) / sizeof((x)[0])))

#ifdef __cplusplus
extern "C" {
#endif
typedef unsigned char uint8_t;
typedef uint8_t byte;

/*
 * Class:     com_jch_test_Logger
 * Method:    e
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL native_error
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
